language: rust
rust: nightly
cache: cargo
before_script:
  - cargo install cargo-web
script:
  - cargo web deploy --release
deploy:
  provider: pages
  local-dir: target/deploy
  skip-cleanup: true
  github-token: $GITHUB_TOKEN  # Set in travis-ci.org dashboard, marked secure
  keep-history: true
  on:
    branch: master
